### ISSUE TITLE
Single Tap isn't strict

### ISSUE THREAD

**Issue by Perfomer** [usuiat/Zoomable#177] opened 2024-03-03 08:05 UTC
**Preconditions:**
- I was trying to implement similar behavior as described in #65 issue.
- I have `HorizontalPager` with pictures and I want to toggle UI on tap.
- Version of Zoomable: 1.6.0
- Version of Compose Foundation (contains Pager): 1.6.2
- Device: Pixel 8, Android 14

**Problem:**
I faced the issue when `onTap` callback invokes by swipe gesture, not a tap.
It reproduces when you swipe slightly so Pager even doesn't change the page.

You can see it on the video:

https://github.com/usuiat/Zoomable/assets/16479387/56621acd-473e-425c-8cc0-efac99c41d3a

**Code:**
```kotlin
HorizontalPager(
    state = pagerState,
    modifier = Modifier.fillMaxSize()
) { page ->
    val zoomState = rememberZoomState()
    AsyncImage(
        model = state.picturesUri[page],
        contentDescription = null,
        onSuccess = { pictureState -> zoomState.setContentSize(pictureState.painter.intrinsicSize) },
        contentScale = ContentScale.Fit,
        modifier = Modifier
            .fillMaxSize()
            .zoomable(
                zoomState = zoomState,
                enableOneFingerZoom = false,
                onTap = {
                    Log.d("MyTag", "onTap() triggered")
                    onPagerClick() // <<< Hide UI in onPagerClick()
                },
            )
        )
}
```

**Ask:**
Could you please make the `onTap` callback more strict, so it doesn't trigger with slight swipes?

**Comment by usuiat** [comment] 2024-03-07 12:45
@Perfomer 
Thank you for creating an issue.

Could you try [v1.6.1-beta01](https://github.com/usuiat/Zoomable/releases/tag/v1.6.1-beta01)?

I found that sometimes HorizontalPager scrolling and Zoomable onTap evnet can occur at the same time.
The cause was that Zoomable did not cancel gesture handling when the parent composable consumed PointerEvents.

Now I fixed to cancel gesture handling.

**Comment by usuiat** [comment] 2024-03-07 23:51
Good!
I will close this issue and will release v1.6.1.

**Closed by usuiat** 2024-03-07 23:51 UTC
